version: '3.3'
services:
    chatgpt-proxy:
        image: chatgpt-proxy-v4
        container_name: chatgpt-proxy-v4
        ports:
            - '8080:8080'
        build:                                         #基于Dockerfile文件构建镜像时使用的属性
            context: .
            dockerfile: Dockerfile
